import LocalizedStrings from 'react-native-localization';

export let strings = new LocalizedStrings({
  kz: {
    tab1: 'Күнтізбе',
    tab2: 'Жазбалар',
    tab3: 'Серпер',
    tab4: 'Әмиян',
    tab5: 'Профиль',
    bast: 'Бастау',
    log: 'Әлі аккаунтыңыз жоқ па?',
    tirk: 'ТІРКЕЛУ',
    pwd: 'Құпия сөз',
    kiru: 'Кіру',
    zab: 'Құпия сөзді ұмыттыңыз ба?',
    neme: 'немесе',
    imya: 'Аты жөніңіз',
    nazad: 'Артқа',
    umytt: 'Құпия сөзді ұмыттым',
    umyttt: 'Құпия сөзді қалпына келтіру үшін тіркелген поштаңызды жазыңыз',
    voss: 'Қалпына келтіру',
    email: 'Поштаңызды тексеріңіз',
    pcht: 'Сіздің ',
    pcht2:
      ' поштаңызға сілтеме жіберілді. Жаңа құпия сөз орнату үшін сілтеме бойынша өтіңіз.',
    neperr: 'Электрондық пошта қате',
    search: 'Іздеу',
    zam: 'Жазбалар',
    papka: 'Папкалар',
    zametnet: 'Сізде Жазбалар жоқ',
    otm: 'Артқа',
    redPr: 'Профильді өңдеу',
    istr: 'Тапсырмалар тарихы',
    uved: 'Хабарламалар',
    lang: 'Тілді өзгерту',
    edPwd: 'Құпия сөзді өзгерту',
    onas: 'Біз туралы',
    oprog: 'Бағдарлама туралы',
    exit: 'Профильден шығу',
    vyi: 'Аккаунттан шынымен шыққыңыз келе ме?',
    bs: 'Қолданбаны әзірлеген',
    jab: 'Тапсырманы көру',
    uvednot: 'Сізде ешқандай хабарламалар жоқ',
    ques: 'Тапсырмалар тарихы',
    bugjet: 'Бүгінгі жетістік',
    kaldy: 'тапсырма қалды',
    edeit: 'Өзгерту',
    vnim: 'Назар аударыңыз',
    oldpwd: 'Қазіргі құпия сөз',
    newpwd: 'Жаңа құпия сөз',
    newpwd2: 'Құпия сөз қайталаңыз',
    save: 'Сақтау',
    cat: 'Санаттар',
    rek: 'Ұсынамыз',
    kiris: 'Кіріс',
    moik: 'Әмияндарым',
    ras: 'Шығындар',
    bastar: 'Бас тарту',
    tem: 'Tақырып',
    addw: 'Әмиян қосу',
    addgoal: 'Мақсат қосу',
    nameW: 'Әмиян аты',
    fio: 'Аты жөні',
    bugjet2: 'Бүгінгі\nжетістік',
    raspr: 'Күн тәртібі',
    week: 'Апта',
    today: 'Бүгін',
    month: 'Ай',
    dobz: 'Тапсырма қосу',
    address: 'мекен-жәй',
    zamk: 'Жазба қосу',
    addzamk: 'Заметкаға қосу',
    reminder: 'Ескерту',
    adetk: 'Әдет қосу',
    adets: 'Әдеттер',
    kosu: 'Қосу',
    vremya: 'Уақыт',
    maks: 'Мақсат қосу',
    kunder: 'Күндер',
    audar: 'Аудару',
    iconch: 'Шартты иконка таңдау',
    fon: 'Фон түсі',
    icons: 'Белгішелер',
    stor: 'Шығындар тарихы',
    stordo: 'Кірістер тарихы',
    books: 'Кітаптар',
    dua: 'Дұға',
    auidoBooks: 'Аудиокітаптар',
    book: 'Кітап',
    kupp: 'Сатып алу',
    oky: 'Оқу',
    mybooks: 'Менің кітаптарым',
    mygoals: 'Менің мақсаттарым',
    filed: 'Файлды өшіргіңіз келеді ме?',
    delete: 'Өшіру',
    process: 'Орындалуда',
    done: 'Орындалды',
    perday: 'күніне',
  },
  ru: {
    tab1: 'Календарь',
    tab2: 'Заметки',
    tab3: 'Медитация',
    tab4: 'Кошелек',
    tab5: 'Профиль',
    bast: 'Начинать',
    log: 'Еще нет учетной записи?',
    tirk: 'РЕГИСТРАЦИЯ',
    pwd: 'Пароль',
    kiru: 'Вход',
    zab: 'Забыл пароль',
    neme: 'или войти через',
    imya: 'Имя Фамилия',
    nazad: 'Нaзaд',
    umytt: 'Забыл пароль',
    umyttt:
      'Введите свой зарегистрированный адрес электронной почты, чтобы сбросить пароль',
    voss: 'Восстановить',
    email: 'Поштаңызды тексеріңіз',
    pcht: 'Ссылка была отправлена ​​на вашу электронную почту ',
    pcht2: '. Перейдите по ссылке, чтобы установить новый пароль.',
    neperr: 'Неправильный Е-mail',
    search: 'Поиск',
    zam: 'Заметки',
    papka: 'Папки',
    zametnet: 'У вас нет заметки',
    otm: 'Отмена',
    redPr: 'Редактировать профиль',
    istr: 'История заданий',
    uved: 'Уведомления',
    lang: 'Сменить язык',
    edPwd: 'Изменить пароль',
    onas: 'О нас',
    oprog: 'О программе',
    exit: 'Выйти из профиля',
    vyi: 'Вы действительно хотите выйти из аккаунта?',
    bs: 'Разработка приложения',
    jab: 'Смотрите, что не закрыто',
    uvednot: 'У вас нет уведомлений',
    ques: 'История заданий',
    bugjet: 'Сегодняшний успех',
    kaldy: 'задача осталась',
    edeit: 'Изменять',
    vnim: 'Внимание',
    oldpwd: 'Текущий пароль',
    newpwd: 'Новый пароль',
    newpwd2: 'Повторить пароль',
    save: 'Сохранить',
    cat: 'Категории',
    rek: 'Рекомендуем',
    kiris: 'Доход',
    moik: 'Мои кошельки',
    ras: 'Расходы',
    bastar: 'Отказать',
    tem: 'Темa',
    addw: 'Добавить кошелек',
    addgoal: 'Добавить цел',
    nameW: 'Название кошелька',
    fio: 'ФИО',
    bugjet2: 'Сегодняшний\nуспех',
    raspr: 'Распорядок дня',
    week: 'Неделя',
    today: 'Сегодня',
    month: 'Месяц',
    dobz: 'Добавить задачу',
    address: 'адрес',
    zamk: 'Добавить примечание',
    addzamk: 'Добавить в заметку',
    reminder: 'Напоминание',
    adetk: 'Добавить привычку',
    adets: 'Привычки',
    kosu: 'Добавить',
    vremya: 'Время',
    maks: 'Добавить цель',
    kunder: 'Дни',
    audar: 'Перевод',
    iconch: 'Условный выбор значка',
    fon: 'Цвет фона',
    icons: 'Иконки',
    stor: 'История расходов',
    stordo: 'История доходов',
    books: 'Книги',
    dua: 'Дуа',
    auidoBooks: 'Aудиокниги',
    book: 'Книгa',
    kupp: 'Kупить',
    oky: 'Читать',
    mybooks: 'Мои книги',
    mygoals: 'Мои цели',
    filed: 'Вы хотите удалить файл?',
    unt: 'Атаусыз',
    delete: 'Удалить',
    process: 'В процессе',
    done: 'Сделано',
    perday: 'в день',
  },
  en: {
    tab1: 'Calendar',
    tab2: 'Notes',
    tab3: 'Meditation',
    tab4: 'Wallet',
    tab5: 'Profile',
    bast: 'Start',
    log: `Don't have an account yet?`,
    tirk: 'REGISTER',
    pwd: 'Password',
    kiru: 'Login',
    zab: 'Forgot password',
    neme: 'or login with',
    imya: 'Name Surname',
    nazad: 'Back',
    umytt: 'Forgot password',
    umyttt: 'Enter your registered email address to reset your password',
    voss: 'Restore',
    email: 'Postaңyzdy tekserіңіz',
    pcht: 'A link has been sent to your email',
    pcht2: '. Follow the link to set a new password. ',
    neperr: 'Invalid E-mail',
    search: 'Search',
    zam: 'Notes',
    papka: 'Folders',
    zametnet: 'You have no note',
    otm: 'Cancel',
    redPr: 'Edit Profile',
    istr: 'Job History',
    uved: 'Notifications',
    lang: 'Change language',
    edPwd: 'Change Password',
    onas: 'About us',
    oprog: 'About the program',
    exit: 'Exit profile',
    vyi: 'Are you sure you want to log out?',
    bs: 'Application Development',
    jab: `See what's not closed`,
    uvednot: 'You have no notifications',
    ques: 'Quest History',
    bugjet: `Today's success`,
    kaldy: 'task left',
    edeit: 'Modify',
    vnim: 'Attention',
    oldpwd: 'Current password',
    newpwd: 'New password',
    newpwd2: 'Repeat password',
    save: 'Save',
    cat: 'Categories',
    rek: 'Recommended',
    kiris: 'Income',
    moik: 'My wallets',
    ras: 'Costs',
    bastar: 'Refuse',
    tem: 'Theme',
    addw: 'Add wallet',
    addgoal: 'Add goal',
    nameW: 'Wallet name',
    fio: 'Name',
    bugjet2: `Today's \nsuccess`,
    raspr: 'Daily routine',
    week: 'Week',
    today: 'Today',
    month: 'Month',
    dobz: 'Add task',
    address: 'address',
    zamk: 'Add note',
    addzamk: 'Add to note',
    reminder: 'Reminder',
    adetk: 'Add a habit',
    adets: 'Habits',

    kosu: 'Add',
    vremya: 'Time',
    maks: 'Add target',
    kunder: 'Days',
    audar: 'Translation',
    iconch: 'Conditional icon selection',
    fon: 'Background color',
    icons: 'Icons',
    stor: 'History of expenses',
    stordo: 'History of income',
    books: 'Books',
    dua: 'Dua',
    auidoBooks: 'Audiobooks',
    book: 'Book',
    kupp: 'Buy',
    oky: 'Read',
    mybooks: 'My books',
    mygoals: 'My goals',
    filed: 'Do you want to delete the file?',
    unt: 'Untitled',
    delete: 'Delete',
    process: 'In process',
    done: 'Done',
    perday: 'per day',
  },
});
